services:
    node_api:
        container_name: node_api
        build: .
        image: node-18:alpine
        ports:
            - '${SERVER_PORT}:${SERVER_PORT}'
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_HOST=${MYSQL_HOST}
        depends_on:
            - node_db
        networks:
            - default

    node_db:
        container_name: node_db
        image: mysql
        ports:
            - '3306:3306'
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - node_db_data:/var/lib/mysql
        networks:
            - default

volumes:
    node_db_data: {}

networks:
    default:
        driver: bridge
